### ISSUE TITLE
PlatformException(ExtAudioOpenURL error, ExtAudioOpenURL error, null, null)

### ISSUE THREAD

**Issue by han-tm** [ryanheise/just_waveform#21] opened 2022-06-27 06:11 UTC
Hi. I get this error when try extract file from audio.

`PlatformException(ExtAudioOpenURL error, ExtAudioOpenURL error, null, null).`

This is only in the iOS version. Everything works fine on android.

Thera are my files path:

_file:///Users/user/Library/Developer/CoreSimulator/Devices/DAB4C89D-6849-460A-A4C7-C1E2D7A81125/data/Containers/Data/Application/D7974DA8-ED71-480B-B289-36CE72899032/tmp/BDC72317-B389-4F46-8CE3-1A24A37172A9.m4a_

_file:///Users/user/Library/Developer/CoreSimulator/Devices/DAB4C89D-6849-460A-A4C7-C1E2D7A81125/data/Containers/Data/Application/D7974DA8-ED71-480B-B289-36CE72899032/tmp/BDC72317-B389-4F46-8CE3-1A24A37172A9.wave_

I am working on a simulator, can this be the problem?

**Comment by ryanheise** [comment] 2022-06-27 07:24
Can you test whether that file path can be played by just_audio? That will tell you whether the file is actually decodable by iOS at all.

**Comment by han-tm** [comment] 2022-06-27 07:44
Yes. The error was due to path. There was an extra prefix  `"file://"`  in the path. 

I don't understand why this prefix is added.

**Comment by ryanheise** [comment] 2022-06-27 08:28
Glad you identified the cause, and since it's not a just_waveform issue I'll close this.

**Closed by ryanheise** 2022-06-27 08:28 UTC
