### ISSUE TITLE
large mp3 file size error

### ISSUE THREAD

**Issue by putheng** [ryanheise/just_waveform#8] opened 2022-02-12 06:29 UTC
When I try to load an mp3 file around 3mb it returns the error 
`PlatformException(ExtAudioOpenURL error, ExtAudioOpenURL error, null, null)`

Have you tested with any max large files?

**Comment by ryanheise** [comment] 2022-02-12 07:34
I'm not sure if that's due to the size of the file or the format of the file or the permissions of the file. Can you provide a minimal reproduction project?

**Comment by putheng** [comment] 2022-02-12 08:16
Hi @ryanheise ,
The problem is format of the file.
Thank you for your package, by the way, did you plan to implement cache? because for now, it has to extract every time we play that mp3 file and some large files it a bit take time to extract.

**Comment by ryanheise** [comment] 2022-02-12 08:50
There is no need for this package to implement a cache since it is intended to focus on just the one responsibility of extracting the waveform, (hence the naming "just"). An app can choose the cache the result if it wants.

**Comment by ryanheise** [comment] 2022-02-12 10:01
Are you happy to close the issue?

**Closed** 2022-02-12 10:11 UTC
